Repository Hae-Rong-E-s/HaeLog-BE, pull requests merged in 2022-12, with the labels that each got.

#6 [feat] 게시글 생성 기능 추가
  src/main/java/com/example/haelogproject/common/response/ResponseDto.java
  src/main/java/com/example/haelogproject/post/controller/PostController.java
  src/main/java/com/example/haelogproject/post/dto/PostRequestDto.java
  src/main/java/com/example/haelogproject/post/dto/PostResponseDto.java
  src/main/java/com/example/haelogproject/post/entity/PostTag.java
  src/main/java/com/example/haelogproject/post/entity/Tag.java
  src/main/java/com/example/haelogproject/post/mapper/PostMapper.java
  src/main/java/com/example/haelogproject/post/repository/PostTagRepository.java
  src/main/java/com/example/haelogproject/post/repository/TagRepository.java
  src/main/java/com/example/haelogproject/post/service/PostService.java
  src/main/java/com/example/haelogproject/tag/repository/TagRepository.java
Labels: feature

#8 [feat] member 회원가입, 아이디 체크, 닉네임 체크, 로그인 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/example/haelogproject/HaelogprojectApplication.java
  src/main/java/com/example/haelogproject/common/exception/CommonExceptionHandler.java
  src/main/java/com/example/haelogproject/common/exception/CustomException.java
  src/main/java/com/example/haelogproject/common/exception/ExceptionMessage.java
  src/main/java/com/example/haelogproject/common/jwt/JwtAuthFilter.java
  src/main/java/com/example/haelogproject/common/jwt/JwtUtil.java
  src/main/java/com/example/haelogproject/common/jwt/exception/CustomSecurityException.java
  src/main/java/com/example/haelogproject/common/jwt/exception/JwtExceptionHandlerFilter.java
  src/main/java/com/example/haelogproject/common/response/ResponseDto.java
  src/main/java/com/example/haelogproject/common/security/UserDetailsImpl.java
  src/main/java/com/example/haelogproject/common/security/UserDetailsServiceimpl.java
  src/main/java/com/example/haelogproject/common/security/WebSecurityConfig.java
  src/main/java/com/example/haelogproject/member/controller/MemberController.java
  src/main/java/com/example/haelogproject/member/dto/RequestUserLogin.java
  src/main/java/com/example/haelogproject/member/dto/RequestUserSignup.java
  src/main/java/com/example/haelogproject/member/dto/ResponseDto.java
  src/main/java/com/example/haelogproject/member/entity/Member.java
  src/main/java/com/example/haelogproject/member/mapper/MemberMapper.java
  src/main/java/com/example/haelogproject/member/repository/MemberRepository.java
  src/main/java/com/example/haelogproject/member/repository/MemberRespository.java
  src/main/java/com/example/haelogproject/member/service/MemberService.java
  src/main/java/com/example/haelogproject/member/service/Validator.java
  src/main/resources/application.properties
Labels: enhancement

#7 [feat] comment 작성, 수정, 삭제 기능 추가
  src/main/java/com/example/haelogproject/HaelogprojectApplication.java
  src/main/java/com/example/haelogproject/comment/controller/CommentController.java
  src/main/java/com/example/haelogproject/comment/dto/RequestCommentDto.java
  src/main/java/com/example/haelogproject/comment/entity/Comment.java
  src/main/java/com/example/haelogproject/comment/mapper/CommentMapper.java
  src/main/java/com/example/haelogproject/comment/service/CommentService.java
  src/main/java/com/example/haelogproject/post/entity/Post.java
Labels: enhancement

#11 [add] security 관련 코드 추가 및 https healthy 관련 Controller 추가
  src/main/java/com/example/haelogproject/common/jwt/JwtAuthFilter.java
  src/main/java/com/example/haelogproject/common/security/HealthyCheckController.java
  src/main/java/com/example/haelogproject/common/security/WebSecurityConfig.java
Labels: enhancement

#13 [feat] 로그인 시에 nickname 이 포함된 data 값 반환
  src/main/java/com/example/haelogproject/member/controller/MemberController.java
  src/main/java/com/example/haelogproject/member/dto/ResponseDto.java
  src/main/java/com/example/haelogproject/member/dto/ResponseUserLogin.java
  src/main/java/com/example/haelogproject/member/service/MemberService.java
Labels: enhancement

#16 [feat] 게시글 상세 조회시 댓글 작성자 확인 기능 추가
  out/production/resources/application.properties
  src/main/java/com/example/haelogproject/post/dto/CommentResponseDto.java
  src/main/java/com/example/haelogproject/post/service/PostService.java
Labels: feature

#18 [add] 비밀번호 단방향 암호화 작업 추가
  src/main/java/com/example/haelogproject/member/mapper/MemberMapper.java
  src/main/java/com/example/haelogproject/member/service/MemberService.java
Labels: enhancement

#20 [fix] 게시물 상세조회 오류 수정
  src/main/java/com/example/haelogproject/post/service/PostService.java
Labels: bug

#19 [add] member 도메인에 필요한 Exception 클래스와 handler 클래스 추가
  src/main/java/com/example/haelogproject/common/exception/CommonExceptionHandler.java
  src/main/java/com/example/haelogproject/common/exception/CustomException.java
  src/main/java/com/example/haelogproject/common/exception/ExceptionMessage.java
  src/main/java/com/example/haelogproject/member/exception/MemberExceptionHandler.java
  src/main/java/com/example/haelogproject/member/exception/custom/DuplicateLoginIdException.java
  src/main/java/com/example/haelogproject/member/exception/custom/DuplicateNicknameException.java
  src/main/java/com/example/haelogproject/member/exception/custom/InvalidLoginIdException.java
  src/main/java/com/example/haelogproject/member/exception/custom/InvalidNicknameException.java
  src/main/java/com/example/haelogproject/member/exception/custom/InvalidPasswordException.java
  src/main/java/com/example/haelogproject/member/exception/custom/LoginIdNotFoundException.java
  src/main/java/com/example/haelogproject/member/exception/custom/WrongPasswordException.java
Labels: enhancement

#23 [feat] 댓글작성 시, data 반환
  src/main/java/com/example/haelogproject/comment/controller/CommentController.java
  src/main/java/com/example/haelogproject/comment/dto/ResponseCommentDto.java
  src/main/java/com/example/haelogproject/comment/service/CommentService.java
  src/main/java/com/example/haelogproject/post/dto/PostDetailResponseDto.java
  src/main/java/com/example/haelogproject/post/mapper/PostMapper.java
  src/main/java/com/example/haelogproject/post/service/PostService.java
Labels: enhancement

#25 [feat] connectRds
  .gitignore
  build.gradle
  src/main/java/com/example/haelogproject/HaelogprojectApplication.java
  src/main/java/com/example/haelogproject/common/security/WebSecurityConfig.java
  src/main/java/com/example/haelogproject/member/exception/MemberExceptionHandler.java
  src/main/java/com/example/haelogproject/post/service/PostService.java
Labels: enhancement

#24 [feat] 유저 정보 조회 기능 추가
  src/main/java/com/example/haelogproject/member/controller/MemberController.java
  src/main/java/com/example/haelogproject/member/dto/RequestUserLogin.java
  src/main/java/com/example/haelogproject/member/dto/ResponseMemberInfo.java
  src/main/java/com/example/haelogproject/member/service/MemberService.java
Labels: enhancement

#22 [add] 각 도메인의 Exception 추가 및 반영
  src/main/java/com/example/haelogproject/comment/exception/CommentExceptionHandler.java
  src/main/java/com/example/haelogproject/comment/exception/custom/CommentNotFoundException.java
  src/main/java/com/example/haelogproject/comment/exception/custom/UnauthorizedCommentException.java
  src/main/java/com/example/haelogproject/comment/service/CommentService.java
  src/main/java/com/example/haelogproject/common/exception/ExceptionMessage.java
  src/main/java/com/example/haelogproject/member/exception/MemberExceptionHandler.java
  src/main/java/com/example/haelogproject/member/exception/custom/MemberNotFoundException.java
  src/main/java/com/example/haelogproject/member/service/MemberService.java
  src/main/java/com/example/haelogproject/post/exception/PostExceptionHandler.java
  src/main/java/com/example/haelogproject/post/exception/custom/PostNotFoundException.java
  src/main/java/com/example/haelogproject/post/exception/custom/TagNotFoundException.java
  src/main/java/com/example/haelogproject/post/exception/custom/UnauthorizedPostException.java
  src/main/java/com/example/haelogproject/post/service/PostService.java
Labels: enhancement
